//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyClase02.Models.Conection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConectionBD : DbContext
    {
        public ConectionBD()
            : base("name=ConectionBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Categoria> tb_Categoria { get; set; }
        public virtual DbSet<tb_Cliente> tb_Cliente { get; set; }
        public virtual DbSet<tb_Colaborador> tb_Colaborador { get; set; }
        public virtual DbSet<tb_ContactoCliente> tb_ContactoCliente { get; set; }
        public virtual DbSet<tb_Meta> tb_Meta { get; set; }
        public virtual DbSet<tb_Producto> tb_Producto { get; set; }
        public virtual DbSet<tb_Rol> tb_Rol { get; set; }
        public virtual DbSet<tb_SemanaPlanificada> tb_SemanaPlanificada { get; set; }
        public virtual DbSet<tb_TipoDocumento> tb_TipoDocumento { get; set; }
        public virtual DbSet<tb_Ubigeo> tb_Ubigeo { get; set; }
    }
}
